version: '3.5'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mypass
    networks:
      - twnet

networks:
  twnet:
