version: '3.5'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mypass
    networks:
      - twnet
  
  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   restart: always
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: mypass
  #   links:
  #     - mongo
  #   depends_on:
  #     - mongo

networks:
  twnet:
